server:
  port: 80


eureka:
  client:
    service-url:
      #单机版 defaultZone: http://127.0.0.1:7001/eureka
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka  # 集群版

spring:
  application:
    name: cloud-order-service